services:
  - type: web
    name: trends
    env: python
    buildCommand: pip install -r requirements.txt
      python manage.py migrate app
    startCommand: "gunicorn trends.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "trends.settings"
      # Add a setup command to run migrations before starting the server
    setupCommand: |
        python manage.py migrate --noinput

